#!/usr/bin/env python3
"""
One-time migration: copy risk_explanation values from the local Docker
PostgreSQL into the Neon (remote) PostgreSQL predictions table.

The explanations were generated by generate_explanations.py locally and
need to be pushed to Neon so the deployed app has access to them.

Usage:
    NEON_DB_URL='postgresql://...' py -3 intelligence/import_explanations.py

    Or add NEON_DB_URL to your .env and just run:
    py -3 intelligence/import_explanations.py
"""

import os
import sys
from dotenv import load_dotenv
import psycopg2
from psycopg2.extras import execute_values

load_dotenv()


def get_local_connection():
    return psycopg2.connect(
        host=os.environ.get("DB_HOST", "localhost"),
        port=os.environ.get("DB_PORT", "5432"),
        user=os.environ.get("DB_USER", "rocketuser"),
        password=os.environ.get("DB_PASSWORD", "rocketpass"),
        dbname=os.environ.get("DB_NAME", "rocket_elevators"),
    )


def main():
    neon_url = os.environ.get("NEON_DB_URL")
    if not neon_url:
        print("ERROR: NEON_DB_URL is not set.")
        print("  Add it to your .env or pass it inline:")
        print("  NEON_DB_URL='postgresql://...' py -3 intelligence/import_explanations.py")
        sys.exit(1)

    # ── Step 1: read from local Docker DB ────────────────────────────────────
    print("Connecting to source (local Docker)...")
    try:
        src = get_local_connection()
    except Exception as exc:
        print(f"ERROR: could not connect to local DB: {exc}")
        print("Is docker-compose up running?")
        sys.exit(1)

    print("Fetching explanations...")
    with src.cursor() as cur:
        cur.execute("""
            SELECT elevator_id, risk_explanation
            FROM predictions
            WHERE risk_explanation IS NOT NULL
              AND risk_explanation <> ''
        """)
        rows = cur.fetchall()
    src.close()
    print(f"  Found {len(rows)} explanations in local DB")

    if not rows:
        print("No explanations found locally. Run generate_explanations.py first.")
        sys.exit(1)

    # ── Step 2: apply to Neon ─────────────────────────────────────────────────
    print("Connecting to destination (Neon)...")
    try:
        dst = psycopg2.connect(neon_url)
    except Exception as exc:
        print(f"ERROR: could not connect to Neon: {exc}")
        sys.exit(1)

    print("Applying updates...")
    with dst.cursor() as cur:
        execute_values(
            cur,
            """
            UPDATE predictions AS p
            SET risk_explanation = v.explanation
            FROM (VALUES %s) AS v(elevator_id, explanation)
            WHERE p.elevator_id = v.elevator_id
            """,
            rows,
            template="(%s, %s)",
            page_size=500,
        )
        updated = cur.rowcount

    dst.commit()
    dst.close()

    print(f"  Updated {updated} rows in Neon predictions table")
    print("Done — risk_explanation is now populated on Neon.")


if __name__ == "__main__":
    main()
